#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2026 Jiaxing Hu <gahing@gahingwoo.com>
"""
Generate the \\p{L} and \\p{N} range tables the pre-tokenizer needs.

The pre-tokenizer is specified as a Unicode regex, so "is this codepoint a
letter" has to be the real Unicode answer and not a guess by block. A hand
written approximation was wrong on Hebrew and Arabic punctuation, which reads
as a letter if you assume the block is alphabetic, and every token id after
one of those moved.

    tools/gen_unicode_tables.py > src/unicode_tables.h
"""

import sys
import unicodedata


def ranges(cats):
    out = []
    start = None
    prev = None
    for cp in range(0x110000):
        hit = unicodedata.category(chr(cp)) in cats
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, prev))
            start = None
        if hit:
            prev = cp
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit(name, rs):
    print("static const uint32_t %s[] = {" % name)
    for i in range(0, len(rs), 4):
        row = "".join("0x%05x, 0x%05x,  " % r for r in rs[i:i + 4])
        print("\t" + row.rstrip())
    print("};")
    print()


def main():
    letters = ranges({"Lu", "Ll", "Lt", "Lm", "Lo"})
    numbers = ranges({"Nd", "Nl", "No"})

    print("/* SPDX-License-Identifier: GPL-2.0-or-later */")
    print("/* Copyright (c) 2026 Jiaxing Hu <gahing@gahingwoo.com> */")
    print("/*")
    print(" * GENERATED by tools/gen_unicode_tables.py from Unicode %s."
          % unicodedata.unidata_version)
    print(" * Do not edit; regenerate.")
    print(" *")
    print(" * %d letter ranges, %d number ranges." % (len(letters), len(numbers)))
    print(" */")
    print("#ifndef CHARSIU_UNICODE_TABLES_H")
    print("#define CHARSIU_UNICODE_TABLES_H")
    print()
    print("#include <stdint.h>")
    print()
    emit("g_letter_ranges", letters)
    emit("g_number_ranges", numbers)
    print("#endif /* CHARSIU_UNICODE_TABLES_H */")
    return 0


if __name__ == "__main__":
    sys.exit(main())
